// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chrips.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createChrip = `-- name: CreateChrip :one
INSERT INTO chrips (id, created_at, updated_at, body, user_id)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2
)
RETURNING id, created_at, updated_at, body, user_id
`

type CreateChripParams struct {
	Body   string
	UserID uuid.UUID
}

func (q *Queries) CreateChrip(ctx context.Context, arg CreateChripParams) (Chrip, error) {
	row := q.db.QueryRowContext(ctx, createChrip, arg.Body, arg.UserID)
	var i Chrip
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}
